language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nerdcorech/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nerdcorech/multi-client-test npm run test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t nerdcorech/multi-client -f ./client/Dockerfile.dev ./client
  - docker build -t nerdcorech/multi-nginx -f ./nginx/Dockerfile.dev ./nginx
  - docker build -t nerdcorech/multi-server -f ./server/Dockerfile.dev ./server
  - docker build -t nerdcorech/multi-worker -f ./worker/Dockerfile.dev ./worker
  - docker push nerdcorech/multi-client
  - docker push nerdcorech/multi-nginx
  - docker push nerdcorech/multi-server
  - docker push nerdcorech/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-045015727085"
  bucket_path: "multi-docker"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
